import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000" # Adjust this URL if your FastAPI app runs on a different port or host


st.set_page_config(
    page_title = "Agentic AI Trip Planner",
    page_icon = "🗺️",
    layout = "centered",
    initial_sidebar_state = "expanded",
)

st.title("AI Trip Planner")

# Intialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []



st.header("Plan Your Trip with AI")

with st.form("query_form"):
    user_input= st.text_input(
        "Ask a question about your trip", placeholder="e.g., What are the best places to visit in Paris?")
    submit_button= st.form_submit_button("Submit")

if submit_button and user_input.strip():
    

    # call the FastAPI endpoint
    try:
        response = requests.post(f"{BASE_URL}/query", json={"query": user_input})
        response.raise_for_status()  # Raise an error for bad responses
        
        if response.status_code == 200:
            answer = response.json().get("response", "No response from server")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(f"**AI:** {answer}")
        else:
            st.error(f"Error: {response.status_code} - {response.text}")

    except Exception as e:
        raise f"An error occurred while processing your request: {str(e)}"


